### PR TITLE
[lecture_notes] notes for Ming-Ho

### PR DESCRIPTION
**Pull request by bennn**

### CODE REVIEW

**Comment by gasche** [comment]
My own notes are as follows:

```
# Dynamo

   Bala et al., PLDI 2000

# Trace trees
   Gal, Franz  Technical Report 2006

   (associated to a workshop publication: HotpathVM, Gal, Probst,
   Franz, VEE 2006)

The mechanism starts as Dynamo, but at the level of JVM bytecode instead of assembly code:

  1. Identify anchor node (target of a backward branch)
  2. If threshold is met, start recording
  3. Stop recording when cycles are found
  4. Emit bytecode for the recorded trace

but they add an extra ingredient, which is to record branches to other
hot traces,

  5. If branch in middle of trace, copy the tail of the trace until
  the cycle back to the anchor.

Unfortunately this may provoke duplication of trace suffixes, in
particular in the case of two nested loop (the threshold will be met
first by the inner loop's anchor, so traces through the outer loop
will be included, may be large, and are duplicated by path-branching
within the inner loop).

Performance: not as good as Hotspot, but with a minimal
effort. (Compared to the purely-interpreted baseline, Hotspot is 10x
faster, they are 7x faster -- geometric average.) They also compile
faster and uses less memory.

# TraceMonkey

Andreas Gal, Brendan Eich, et al., PLDI 2009

Applying the tracing idea to a Javascript instead of Java
implementation.

Some effort was spent on handling type specialization at the trace
level -- where "type" is a finite set specific value representations
that are of interest for optimization.

Nesting algorithm:

- start tracing a loop trace Lr
- if you exit the loop, abort the trace, throw it out
- if you reach another loop Lo,
  we say that loop trace Lr is inside Lo

  If Lo has a compiled trace (with matching types), call its trace;
  otherwise abort Lr

Looking at performance numbers, we see that tracing is excellent at
bitwise operations. This comes from the fact that Javascript has no
integer type in the surface language, so you need to agressively
specialize types there.

On the other side, V8 was better on most other benchmarks. They found
out that they don't do very well on recursion, regular expressions,
and `eval`.

Mitch: why does V8 do better at recursion?

Ming-Ho: I don't know.

Jan: remark that those benchmarks have nothing at all to do with
website programming. They have been ported from other systems, and
they are not representative.

Ming-Ho: yes, and there was more recent work in 2011 on finding more
representative Javascript benchmarks. Jan?

Jan: yeah, basically they found that tracing JITs don't work at all on
real-world code, it is not general enough.

Matthias: this is a sign of a dead-end! Dead-end are common and really
precious, you should highlight them.

Jan: note that tracing is not inherently bad, it's just that in this
context it doesn't work.

# Pypy, Tracing the Meta-Level

2009
Carl Friedrich Bolz, Antonio Cuni, Maciej Fijałkowski, Armin Rigo

If you blindly trace the interpreter code, your tracing will be wrong:
the loop that will be recognized as a cycle is the
instruction-dispatch loop, but cycle there does not correspond to
a cycle in the interpreted program, just to the execution of *one*
instruction (not much benefit). Instead you need to abstract away the
notion of "code position" that is use for cycle detection, and take
into account the *interpreter*'s program counter (a program-specific
value) for cycle detection: you have seen a cycle when you are back at
the same position in the interpreter program, with the same
interpreter PC.

(As the author of the interpreter, you designate this PC variable to
be handled specially, and also add hints on where backward-jumps may
happen.)

Note that the trace, because it knows about the PC, is in extremely
good place to do partial evaluation: the interpreter code that is
generic on the PC and instruction arguments can be specialized. The
code you get as output is exactly as if the interpreted program had
been traced directly (instead of meta-traced).

Jan: slightly off-target, but recently we added a bytecode compiler to
the R implementation that was only an interpreter. We noticed (to our
surprise) that we were slower on some benchmarks; because a lot of
code was generated at runtime and the compilation overhead was byting
us.

# Loop-aware optimization
Ardö, Bolz, Fijałkowski

Implemented in LuaJIT by Mike Pall, who did not write a paper about it
but invited other researchers to learn about it.

Jan: why is Mike Pall not one of the authors, then?
Ming-Ho: He got special credit in the paper.

# General discussion

Jan: one thing that these papers don't say is that they need a very
long warmup time before getting good numbers. It's a bit iffy because
a lot of time you don't want a long warmup time.

Jan: what is the right methodology to study a self-adapting system? On
the first run, you get all the extra costs. If you wait until it
stabilizes, you get the faster result, but it can take thousands of
iterations.

Leif: has someone done a study of how long it takes to reach the
stable regime?

Jan: yes, Tratt and Bolz worked on this, and it's really fun the
results they get across languages.
```

**Comment by mhyee** [comment]
Thanks @bennn and @gasche! I plan on typesetting my own notes, and I could incorporate the discussions that you recorded. Or would you prefer to post the discussion separately?

**Comment by bennn** [comment]
+1 for incorporating the discussions.

**Comment by mhyee** [comment]
Lecture and discussion notes added in 54d1f9787e25e85b70e4c411bd610ac49267f560.

I'll update and publish the blog post later today.

**Pull request closed without merging**
